language: objective-c
before_install:
- brew install xctool

script:
- xctool -workspace Example/currencyParser.xcworkspace -scheme currencyParser-Example test -sdk iphonesimulator  ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
