# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- brew install xctool
# - pod install --project-directory=Example
# install:
# - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- xctool -workspace Example/currencyParser.xcworkspace -scheme currencyParser-Example test -sdk iphonesimulator  ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick

# xctool -workspace MyApp.xcworkspace -scheme MyApp test
